fragment assetImagerSquare on AssetInterface {
  base64: url @imagerTransform(width: 20, format: "gif", return: "dataUri")
  srcsetLegacy: url @imagerSrcset (handle: "square")
  srcset: url @imagerSrcset (handle: "squareWebp")
}
